import { type NextPage } from "next";
import Head from "next/head";
import Captcha from "@/components/Captcha";
import TextBox from "@/components/TextBox";
import { useState } from "react";


const Home: NextPage = () => {
  const [inputForm, setInputForm] = useState("");
  const [selectedImages, setSelectedImages] = useState<never | number[]>([]);

  function submitForm(e: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
    e.preventDefault();
    if (!inputForm) {
      alert("The message is required");
      return;
    } else {
    }
    fetch("/api/send", {
      method: "POST",
      body: JSON.stringify({
        message: inputForm,
        selectedImages,
      }),
      headers: { "Content-Type": "application/json" },
      credentials: "include" // Menyertakan cookie dalam permintaan
    }).then(res => { console.log(res) });
    
  }
  return (
    <>
      <Head>
        <title>Captcha Component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center gap-14 bg-gradient-to-b from-[#212121] to-app-black-soft px-20">
        <h1 className="text-3xl font-[700] text-white">Captcha</h1>
        <form className="flex w-[300px] flex-col gap-4">
          <TextBox
            value={inputForm}
            name="Text Box"
            placeholder="Input the message"
            setValue={setInputForm}
          />
          <h2 className="flex items-start justify-start text-left text-2xl font-semibold text-white">
            Select all dog
          </h2>
          <Captcha
            selectedImages={selectedImages}
            setSelectedImages={setSelectedImages}
          />
          <button
            type="submit"
            className="mx-auto flex w-[50%] items-center justify-center rounded-md bg-app-red px-4 py-1 text-center font-semibold text-white"
            onClick={(e) => {
              submitForm(e);
            }}
          >
            Send
          </button>
        </form>
      </main>
    </>
  );
};

export default Home;
