import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import Captcha from "@/components/Captcha";
import TextBox from "@/components/TextBox";
import { useState } from "react";

const Home: NextPage = () => {
  const [inputForm, setInputForm] = useState("");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full px-20 flex-col items-center justify-center gap-14 bg-gradient-to-b from-[#212121] to-app-black-soft">
        <h1 className="text-white font-[700] text-3xl">Captcha</h1>
        <form className="flex flex-col gap-4 w-[300px]">
          <TextBox
            value={inputForm}
            name="Text Box"
            placeholder="Input the message"
            setValue={setInputForm}
          />
          <h2 className="text-white font-semibold flex items-start justify-start text-left text-2xl">Select all dog</h2>
          <Captcha/>
          <button
            className="flex w-[50%] items-center mx-auto justify-center rounded-md bg-app-red px-4 py-1 text-center text-white font-semibold"
            onClick={() => {
              console.log("Captcha clicked");
            }}
          >
            Send
          </button>
        </form>
      </main>
    </>
  );
};

export default Home;
